name: Build Android APK

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle


      - name: Check Android project files
        working-directory: ./RONIN_Body_Kotlin
        run: |
          ls -la
          ls -la gradle/wrapper


      - name: Make Gradle wrapper executable
        working-directory: ./RONIN_Body_Kotlin
        run: chmod +x gradlew


      - name: Build Debug APK
        working-directory: ./RONIN_Body_Kotlin
        run: |
          ./gradlew assembleDebug \
          --no-daemon \
          --stacktrace \
          -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError"


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VYRX-debug-apk
          path: RONIN_Body_Kotlin/app/build/outputs/apk/debug/*.apk
